# api paths mapped to services
# set to httpbin.org standard http methods (again, for convenience)
routes:
  - path: /delete
    upstream: https://httpbin.org/
  - path: /get
    upstream: https://httpbin.org/
  - path: /patch
    upstream: https://httpbin.org/
  - path: /post
    upstream: https://httpbin.org/
  - path: /put
    upstream: https://httpbin.org/
  - path: /
    upstream: https://httpbin.org/
